### ISSUE TITLE
Fix cross-platform compatibility

### ISSUE THREAD

**Issue by merijn** [merijn/posix-pty#1]
Currently only compiles on OSX, fix to at least support FreeBSD, OSX and linux.

**Comment by tomjaguarpaw** [comment]
@proger seems to have a fork which supports Linux (at least).  Would you consider merging?  It seems silly to have two packages on Hackage for this.

**Comment by merijn** [comment]
Uploaded version 0.2 which fixes this, exception safety and also add processhandles.
