### ISSUE TITLE
control-d issue

### ISSUE THREAD

**Issue by joeyh** [merijn/posix-pty#11]
I'm using posix-pty to write a program that is similar to the `script` command, that runs bash in a pty and forwards input and output between it and the user's terminal. For some reason, control-d is not being handled in the usual way. Usually, when at the bash prompt and nothing has been typed, control-d will be caught by bash and it runs "exit". Using posix-pty, instead "^D" gets displayed, and bash does not exit.

My program was earlier not using posix-pty and was setting up the pty itself and running a program connected to it using System.Process. In that version, control-d worked as expected. 

My program is reading "\EOT" from the user, and is feeding that into writePty.

I suspect that something about how posix-pty sets up the pty is causing the problem. Perhaps something in `fork_exec_with_pty`?

You can find the two versions of my program here:

* [does not use posix-pty; control-d works](https://git.joeyh.name/index.cgi/debug-me.git/commit/?id=a4a9a6b39a56db45b75da6727d5864a1af4e83ae)
* [uses posix-pty; control-d does not work](https://git.joeyh.name/index.cgi/debug-me.git/commit/?id=cf9eb1f6d1dd9a5a52a9604bff60dcbb766825fe)

**Comment by joeyh** [comment]
Looking at `stty` shows what's going on with control-d, as well as other weird behavior of backspace, etc:

    stty -a
    speed 9600 baud; rows 19; columns 71; line = 0;
    intr = ^D; quit = <undef>; erase = <undef>; kill = ^?; eof = ^W;
    eol = ^Y; eol2 = ^A; swtch = <undef>; start = ^C; stop = ^\; susp = ^Z;
    rprnt = ^Q; werase = ^V; lnext = ^O; discard = ^S; min = 18; time = 21;
    -parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
    -ignbrk brkint -ignpar -parmrk -inpck istrip -inlcr -igncr icrnl ixon
    -ixoff -iuclc ixany imaxbel -iutf8
    opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab3 bs0
    vt0 ff0
    isig icanon iexten echo echoe -echok -echonl -noflsh -xcase -tostop
    -echoprt echoctl echoke -flusho -extproc

Compared with the terminal that was started in:

   speed 38400 baud; rows 19; columns 71; line = 0;
   intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
   eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
   rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
   -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
   -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon
   -ixoff -iuclc -ixany -imaxbel iutf8
   opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0
   vt0 ff0
   isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop
  -echoprt echoctl echoke -flusho -extproc

In particular, intr = ^D seems a strange default, as does kill = ^? (backspace) etc.

**Comment by joeyh** [comment]
The following modification fixed it for me:

    -    *child_pid = forkpty(&pty, NULL, &tio, &ws);
    +    *child_pid = forkpty(&pty, NULL, NULL, &ws);

**Comment by joeyh** [comment]
Looking at my linux system's headers, ttydefchars is the following:

    cc_t    ttydefchars[NCCS] = {
        CEOF,   CEOL,   CEOL,   CERASE, CWERASE, CKILL, CREPRINT,
        _POSIX_VDISABLE, CINTR, CQUIT,  CSUSP,  CDSUSP, CSTART, CSTOP,  CLNEXT,
        CDISCARD, CMIN, CTIME,  CSTATUS, _POSIX_VDISABLE
    };

However, the c_cc array of struct termios is defined as starting with values for VDISCARD, VDSUSP, VEOF, VEOL. So, what seems to have happened is ttydefchars does not include the first 2 of those, and so every control character is mapped to the wrong value.

This is on debian amd64 with headers from glibc 2.24.

**Comment by joeyh** [comment]
Ok, worked around the problem in my program with:

    as <- System.Posix.getTerminalAttributes stdInput
    System.Posix.Pty.setTerminalAttributes pty as Immediately

Actually, I feel my program ought to do that, in case the user has a non-default stty setting etc; I want to explicitly copy that into the pty.

I do think this is a bug in posix-pty though, its attempt to set the defaults on linux fails.

**Comment by merijn** [comment]
Actually, I think this is a "bug" in the way GHC deals with buffering and tty's, not 100% sure, though. I have an idea where to look, but haven't had time yet. Thanks for the report, with some luck I'll have some time to look into it before the weekend.

**Comment by merijn** [comment]
I thought I'd already replied to this, but apparently not. I think you're right, forkpty is supposed to not have a termios config to get a "default" fresh terminal. Now, it's conceivable one might want to specify a custom pty setup before calling the child program, but the API doesn't really easily allow for that at the moment, so I should probably drop all the termios stuff entirely.

**Comment by merijn** [comment]
I'll update the Hackage version as soon as I manage to reset my Hackage password >.>
