### ISSUE TITLE
Forking can interact with runtime to cause livelock (100% cpu usage) or freezing

### ISSUE THREAD

**Issue by thomasjm** [merijn/posix-pty#15]
If `spawnWithPty` is called at an unlucky time (i.e. when other system calls like printing to stderr and launching other processes are happening) then some kind of bad interaction with the runtime can get triggered, resulting in either full CPU livelock (stuck at 100% across all CPUs) or freezing of the Haskell process.

A nice repro (courtesy of u/Noughtmare on Reddit) is below. You can also find my original, slightly more complicated version as a full repo [here](https://github.com/thomasjm/haskell-livelock-repro).

```haskell
module Main where

import Control.Concurrent
import Control.Monad
import System.Posix.Pty
import System.Process

main :: IO ()
main = do
  forkIO $ replicateM_ 1000 $ putStrLn "This is a test"

  -- Repeat this 20 times
  replicateM_ 20 $ do
    forkIO $ void $ spawnWithPty Nothing True "sleep" ["99999999"] (80, 24)
    forkIO $ void $ readCreateProcess (proc "echo" ["hi"]) ""

  -- All CPUs should now be stuck at 100%
  threadDelay 60000000
```

I'm filing this issue after a Reddit discussion which determined that `posix-pty` most likely needs to be more careful about how it forks. You can see the discussion here: https://www.reddit.com/r/haskell/comments/d4h7ty/why_does_this_code_livelock_all_my_cpus_at_100/

**Comment by merijn** [comment]
ok, new version is now on hackage.
